workflow:
  name: 'branch: $CI_COMMIT_BRANCH | Commit: $CI_COMMIT_TITLE'

stages:
  - Code-Sanity
  - Build
  - Test

variables:
  UV_VERSION: "0.9"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: slim
  UV_LINK_MODE: copy

default:
  image: python:$PYTHON_VERSION-$BASE_LAYER

linter:
  stage: Code-Sanity
  before_script:
    - pip install uv
    - cd prototype
  script:
    - uv sync
    - uv run ruff check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

type-checker:
  stage: Code-Sanity
  before_script:
    - pip install uv
    - cd prototype
  script:
    - uv sync
    - uv run ty check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cpp-build:
  stage: Build
  image: ubuntu:24.04
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq
        build-essential
        cmake
        libopencv-dev
  script:
    - cd application         
    - cmake -B build -S .
    - cmake --build build --parallel $(nproc)
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


cpp-test:
  stage: Test
  image: ubuntu:24.04
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq
        build-essential
        cmake
        libopencv-dev
        libgtest-dev
  script:
    - cd application
    - cmake -B build -S . -DBUILD_TESTING=ON
    - cmake --build build --parallel $(nproc)
    - cd build && ctest --output-on-failure
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
